# Generated by Django 2.2.6 on 2019-10-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cronjob_Dev', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronjob',
            old_name='authentification',
            new_name='auth',
        ),
    ]
