# Generated by Django 2.2.6 on 2019-10-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cronjob_Dev', '0002_auto_20191010_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='cronejob',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='password',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='username',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
